version: '3'

services:
  nginx:
    image: nginx:1.14
    container_name:
      beejee_nginx
    ports:
      - 7505:80
    volumes:
      - ../app:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
    networks:
      - internal

  php:
    build:
      ./php
    image: php:beejee
    container_name:
      beejee_php
    volumes:
      - ../app:/usr/share/nginx/html
    depends_on:
      - mariadb
    environment:
      XDEBUG_CONFIG: "remote_host=host.docker.internal remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
    networks:
      - internal

  mariadb:
    image: mariadb:10.3
    restart: always
    container_name:
      beejee_db
    ports:
      - 3344:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mariadb:/var/lib/mysql
    networks:
      - internal

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mariadb:db
    container_name:
      beejee_pma
    ports:
      - 8700:80
    environment:
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mariadb
    networks:
      - internal

networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.220.0/28